name: Deployment-AR

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout source code'
      uses: actions/checkout@v4
    
    - name: Login Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Bicep Validate
      run: |
        az deployment sub validate \
          --name validate-${{ github.run_id }} \
          --template-file ./config/main.bicep \
          --location "westus"

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: ./config/main.bicep
        parameters: 'namePrefix=${{ vars.AZURE_PREFIX }}'
        failOnStdErr: false
